config/routes.rb
Rails.application.routes.draw do
  get 'auth/index'
  resources :user
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :zens
  root "zens#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'static/privacy_policy'
  get 'static/menseki'

  get 'auth/sign_out'
  post 'reports/count'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :zens, class_name: 'Zen'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :zens
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :trackable, :omniauthable, omniauth_providers: %i(google)
  has_one_attached :avatar

  def get_nickname
    return "名無しさん" if self.nickname.blank?
    self.nickname
  end

  protected
  def self.find_for_google(auth)
    user = User.find_by(email: auth.info.email)

    unless user
      user = User.create(
        provider: auth.provider,
        token:    auth.credentials.token,
        email:    auth.info.email
        )
        # password: Devise.friendly_token[0, 20],
        # meta:     auth.to_yaml)
    end
    user
  end
end

app/models/zen.rb
class Zen < ApplicationRecord
    belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  def index
  end

  def sign_out
    cookies.clear
    session.clear
    redirect_to root_path
  end
end

app/controllers/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def google
      @user = User.find_for_google(request.env['omniauth.auth'])
  
      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth']
        redirect_to new_user_registration_url
      end
    end
  
    def after_sign_in_path_for(resource)
      home_index_path
    end
  end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :require_login, only: [:count]

  def count
    report = Report.find_or_initialize_by(zens_id: params[:zens_id])
    binding.pry
    report.increment(:report_count, 1)
    # report.zens_id = params[:zens_id]
    if report.save then
      respond_to do |format|
        format.html { redirect_to zens_url, notice: t(:zen_reported) }
        format.json { head :no_content }
      end
    end
  end

  private
    def require_login
      unless current_user
        redirect_to zens_path, notice: "ログインする必要があります"
      end
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def privacy_policy
    end

    def menseki
    end
end
  

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only: [:edit, :update, :create, :destroy]
  before_action :require_myself, only: [:edit, :update]

  def edit
  end

  def show
    @zens = Zen.where(user_id: params[:id]).where(deleted: false).order("created_at DESC").paginate(page: params[:page], :per_page => 30)
  end

  def update
    respond_to do |format|

      if @user.update(user_params) then
        if params[:user][:avatar] then
            @user.avatar.attach(params[:user][:avatar])
        end
        format.html { redirect_to auth_index_url, notice: t(:nickname_updated) }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:nickname, :avatar)
    end

    def require_login
      unless current_user
        redirect_to auth_index_path, notice: "You must be logged in to access this section"
      end
    end

    def require_myself
      if current_user.id != params[:id].to_i
        redirect_to auth_index_path, notice: "You must be logged in to access this section"
      end
    end
end
  

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def google
      @user = User.find_for_google(request.env['omniauth.auth'])
  
      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth']
        redirect_to new_user_registration_url
      end
    end
  
    def after_sign_in_path_for(resource)
      auth_index_path
    end
  end

app/controllers/zens_controller.rb
class ZensController < ApplicationController
  before_action :set_zen, only: [:show, :edit, :update, :destroy]
  before_action :require_myself, only: [:edit, :update, :destroy]
  before_action :require_login, only: [:create]

  # GET /zens
  # GET /zens.json
  def index
    @zens = Zen.where(deleted: false).order("created_at DESC").paginate(page: params[:page], :per_page => 30)
    if params[:id].present?
      set_zen
    else
      @zen = Zen.new
    end
  end

  # GET /zens/1
  # GET /zens/1.json
  def show
  end

  # GET /zens/1/edit
  def edit
  end

  # POST /zens
  # POST /zens.json
  def create
    model_params = zen_params
    model_params[:user_id] = current_user.id
    @zen = Zen.new(model_params)

    respond_to do |format|
      if @zen.save
        format.html { redirect_to zens_url, notice: '一善が投稿されました。' }
        format.json { render :show, status: :created, location: @zen }
      else
        format.html { render :new }
        format.json { render json: @zen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zens/1
  # PATCH/PUT /zens/1.json
  def update
    respond_to do |format|
      if @zen.update(zen_params)
        format.html { redirect_to zens_url }
        format.json { render :show, status: :ok, location: @zen }
      else
        format.html { render :edit }
        format.json { render json: @zen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zens/1
  # DELETE /zens/1.json
  def destroy
    @zen.destroy
    respond_to do |format|
      format.html { redirect_to zens_url, notice: t(:zen_destroyed) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zen
      @zen = Zen.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zen_params
      params.require(:zen).permit(:content, :deleted)
    end

    def require_login
      unless current_user
        redirect_to zens_path, notice: "ログインする必要があります"
      end
    end

    def require_myself
      if current_user.id != Zen.find(params[:id].to_i).user_id
        redirect_to zens_path, notice: "投稿者本人である必要があります"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def app_url
        ENV['APP_URL'] || ""
    end

    def app_name
        ENV['APP_NAME'].dup.force_encoding('UTF-8') || ""
    end

    def logged_in?
        current_user ? true : false
    end

    # 引数で与えられたユーザーのidenticon画像を返す
    def identicon_for(user, size = 50)
      identicon_url = "https://identicon-api.herokuapp.com/#{user.created_at} + #{user.id.to_s}/#{size}?format=png"
      image_tag(identicon_url, alt: user.nickname, class: "gravatar", size: size)
    end

    def profile_icon_tag(user, size = 50)
        if user.avatar.attached?
            image_tag(user.avatar, alt: user.nickname, class: "gravatar", size: size)
        else
            identicon_for(user, size)
        end
    end
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/zens_helper.rb
module ZensHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="<%= app_url %>"><%= app_name %></a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "プライバシーポリシー", static_privacy_policy_path %></li>
      <li><%= link_to "免責事項", static_menseki_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   app_url %></li>
              <% if logged_in? %>
                <li>
                  <%= link_to "ユーザー情報", auth_index_path %>
                </li>
                <li>
                  <%= link_to "ログアウト", auth_sign_out_path %>
                </li>
              <% else %>
                <li>
                  <%= link_to "新規登録 / ログイン", auth_index_path %>
                </li>
              <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/application.html.erb
</html>
<!DOCTYPE html>
<html>
  <head>
    <title>一日一善</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-Z9FZGV9L8D"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'G-Z9FZGV9L8D');
    </script>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/user/_form.html.erb
<% if current_user %>
  <%= form_with(model: user, local: true, :html => { :multipart => true }) do |form| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
        <%= form.label :avatar %>
        <%= form.file_field :avatar %>
    </div>

    <div class="field">
      <%= form.label :nickname %>
      <%= form.text_area :nickname %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
<% end %>

app/views/user/edit.html.erb
<h1><%= t :editing_user %></h1>

<%= render 'form', user: @user %>

app/views/user/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @zens.first.user.get_nickname %>さんの一善</h1>

<br>
<div class="row">
    <ol class="zens">
    <% @zens.each do |zen| %>
      <li id="zen-<%= zen.id %>">
        <%= link_to profile_icon_tag(zen.user, 50), zen.user %>
        <span class="user"><%= link_to zen.user.get_nickname, zen.user %></span>
        <span class="content"><%= zen.content %></span>
        <span class="timestamp">
        <%= time_ago_in_words(zen.created_at.in_time_zone('Tokyo')) %> 前に投稿されました
        </span>
          <span class="links">
          <td><%= link_to '詳細', zen_path(id: zen.id) %></td>
          <% if current_user && current_user.id == zen.user_id %>
            <td><%= link_to '編集', edit_zen_path(id: zen.id) %></td>
            <td><%= link_to '削除', zen, method: :delete, data: { confirm: t(:are_you_sure) } %></td>
          <% end %>
          </span>
      </li>
    <% end %>
    </ol>

<%= will_paginate @zens %>

<br>
</div>

<%= link_to '一覧へ戻る', zens_path %>

app/views/zens/_form.html.erb
<% if current_user %>
  <%= form_with(model: zen, local: true) do |form| %>
    <% if zen.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(zen.errors.count, "error") %> prohibited this zen from being saved:</h2>

        <ul>
        <% zen.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :content, "一善の内容" %>
      <%= form.text_area :content %>
    </div>

    <% if controller.action_name == 'edit' || (controller.action_name == 'index' && params[:id]) %>
    <div class="field">
      <%= form.label :deleted, "削除する場合はチェック" %>
      <%= form.check_box :deleted %>
    </div>
    <% end %>


    <div class="actions">
      <%= form.submit "自分の一善を投稿する" %>
    </div>
  <% end %>
<% end %>

app/views/zens/edit.html.erb
<h1>Editing Zen</h1>

<%= render 'form', zen: @zen %>

<%= link_to '一覧に戻る', zens_path %>

app/views/zens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>みんなの一善</h1>

<%= render 'form', zen: @zen %>

<br>
<div class="row">
    <ol class="zens">
    <% @zens.each do |zen| %>
      <li id="zen-<%= zen.id %>">
        <%= link_to profile_icon_tag(zen.user, 50), zen.user %>
        <span class="user"><%= link_to zen.user.get_nickname, zen.user %></span>
        <span class="content"><%= zen.content %></span>
        <span class="timestamp">
        <%= time_ago_in_words(zen.created_at.in_time_zone('Tokyo')) %> 前に投稿されました
        </span>
          <span class="links">
          <td><%= link_to '詳細', zen_path(id: zen.id) %></td>
          <td><%= link_to '通報', reports_count_path(zens_id: zen.id), method: :post, data: { confirm: t(:are_you_sure) } %></td>
          <% if current_user && current_user.id == zen.user_id %>
            <td><%= link_to '編集', edit_zen_path(id: zen.id) %></td>
            <td><%= link_to '削除', zen, method: :delete, data: { confirm: t(:are_you_sure) } %></td>
          <% end %>
          </span>
      </li>
    <% end %>
    </ol>

<%= will_paginate %>

<br>
</div>

app/views/zens/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
    <ol class="zens">
      <li id="zen-<%= @zen.id %>">
        <%= link_to profile_icon_tag(@zen.user, 50), @zen.user %>
        <span class="user"><%= link_to @zen.user.get_nickname, @zen.user %></span>
        <span class="content"><%= @zen.content %></span>
        <span class="timestamp">
        <%= time_ago_in_words(@zen.created_at.in_time_zone('Tokyo')) %> 前に投稿されました
        </span>
          <% if current_user && current_user.id == @zen.user_id %>
            <span class="links">
            <%= link_to '編集する', edit_zen_path(@zen) %> |
            <td><%= link_to '削除', @zen, method: :delete, data: { confirm: t(:are_you_sure) } %></td>
            </span>
          <% end %>
      </li>
    </ol>
<br>
</div>

<%= link_to '一覧へ戻る', zens_path %>